- id: doccheck
  name: Run DocCheck embedded tests
  description: Runs embedded docstring tests across the project.
  entry: python -m doccheck
  language: system
  types: [python]
  pass_filenames: false
